// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web_fitness.Data;

namespace web_fitness.Migrations
{
    [DbContext(typeof(fitnessdataContext))]
    [Migration("20200526143240_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("web_fitness.Models.Meetings", b =>
                {
                    b.Property<DateTime>("MeetDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TrainerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeetID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TrainTypeTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MeetDate", "TrainerId", "TypeId");

                    b.HasIndex("TrainTypeTypeId");

                    b.HasIndex("TrainerId");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("web_fitness.Models.Trainers", b =>
                {
                    b.Property<int>("TrainerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(60);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(60);

                    b.Property<string>("Mail")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrainerGender")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrainerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrainerPhone")
                        .HasColumnType("TEXT");

                    b.HasKey("TrainerId");

                    b.ToTable("Trainers");
                });

            modelBuilder.Entity("web_fitness.Models.TrainingType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(60);

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(60);

                    b.HasKey("TypeId");

                    b.ToTable("TrainingTypes");
                });

            modelBuilder.Entity("web_fitness.Models.Meetings", b =>
                {
                    b.HasOne("web_fitness.Models.TrainingType", "TrainType")
                        .WithMany("Meeting")
                        .HasForeignKey("TrainTypeTypeId");

                    b.HasOne("web_fitness.Models.Trainers", "Trainer")
                        .WithMany("Meeting")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
